name: release-edge-tag
on: issue_comment

jobs:
  release-edge-tag:
    runs-on: ubuntu-latest
    steps:
      - name: update release-edge tag
        if: |
          github.event.issue.pull_request &&
          github.event.pull_request.head.ref == 'fix-timing-of-create-release-edge-tag' &&
          startsWith(github.event.comment.body, 'release-edge-')
        run: |
          ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
          aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login -u AWS --password-stdin ${ECR_REGISTRY}
          if [[ "${GITHUB_REF#refs/tags/}" =~ ^release-edge-(r[0-9]{8})$ ]]; then
            image_tag=${BASH_REMATCH[1]}
          fi
          if [[ -z "${image_tag}" ]]; then
            echo "image tag not found"
            exit 1
          fi
          image_url=${ECR_REGISTRY}/${ECR_REPOSITORY}
          docker pull ${image_url}:${image_tag}
          docker tag ${image_url}:${image_tag} ${image_url}:release-edge
          docker push ${image_url}:release-edge
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          ECR_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
